version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "expo"
      - dependency-name: "expo-*"
      - dependency-name: "@expo/*"
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "react-native"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - JG03dev
    labels:
      - "dependencies"
      - "utility"
